### ISSUE TITLE
Cannot build the editor from this code.

### ISSUE THREAD

**Issue by marlon-assef** [Ogmo-Editor-3/Ogmo-Editor-3.github.io#9]
Hi.

I could not build the editor from this code.

Although the title is Ogmo-Editor-3.github.io, I can only build the tile preview.

How can I get the Editor? I try to download from itch.io but received the message "A password is required to view this page".

Regards.

**Comment by AustinEast** [comment]
Hi! Sorry for the late reply - At the moment, the editor is not yet released. When it is, we'll be making the itch page public and putting the editor's source in its own separate repository.

**Comment by AustinEast** [comment]
The editor is out - check ogmo-editor-3.github.io - so im gonna close this issue 👍

**Comment by marlon-assef** [comment]
Thank you @AustinEast I will give it a try.
Best Regards.
